releases:
  - name:    shield
    version: 8.6.0
    url:     https://github.com/shieldproject/shield-boshrelease/releases/download/v8.6.0/shield-8.6.0.tgz
    sha1:    249984b9c4fc983c51d72b951610438551d748cb
