---
params:
  postgres-addon-version: (( param "Please specify the version of the Postgres addon.  Expecting one of 9.0, 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 10, 11" ))

instance_groups:
- name: shield
  jobs:
  - name:    (( concat "shield-addon-postgres-" params.postgres-addon-version ))
    release: shield-addon-postgres

releases:
- name:    shield-addon-postgres
  version: 1.0.2
  url:     https://github.com/shieldproject/shield-addon-postgres-boshrelease/releases/download/v1.0.2/shield-addon-postgres-1.0.2.tgz
  sha1:    45fb8d0c4919c55667cb18ee17e5e333a5eb5789
