---
meta:
  vault: (( concat "secret/" params.vault ))

instance_groups:
  - name: shield
    instances: 1
    azs: (( grab params.availability_zones ))
    persistent_disk_pool: (( grab params.shield_disk_pool ))
    vm_type:              (( grab params.shield_vm_type   ))
    stemcell: ubuntu
    networks:
      - name: (( grab params.shield_network ))
        static_ips: (( grab params.shield_static_ip ))
    jobs:
      - name: postgres
        release: shield
        properties:
          databases:
          - {name: shield,   tag: shield,   citext: true}
          roles:
          - name: shieldadmin
            password: (( vault meta.vault "/database/shield:password" ))
            tag: admin
      - name: shield-daemon
        release: shield
        provides:
          shield-daemon: {shared: true, as: shield-daemon}
        properties:
          name:   (( grab params.installation ))
          domain: (( grab params.shield_static_ip ))
          ssh_private_key: (( vault meta.vault "/agent:private" ))
          auth:
            username: shield
            password:  (( vault meta.vault "/webui:password" ))
            api_keys:
              autoprovision: (( vault meta.vault "/provisioning:key" ))
          ssl:
            crt: (( vault meta.vault "/shield/certs/server:certificate" ))
            key: (( vault meta.vault "/shield/certs/server:key" ))
      - name: shield-agent
        release: shield
        consumes:
          shield-daemon: {from: shield-daemon}
        properties:
          autoprovision: true
          schedules: {default: daily 3am}
          retention-policies: {default: 30}

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
- alias: ubuntu
  os: ubuntu-trusty
  version: latest

releases:
- name: shield
  version: 7.0.1
  url: https://github.com/starkandwayne/shield-boshrelease/releases/download/v7.0.1/shield-7.0.1.tgz
  sha1: 59523e113c2276a54eca308aa1ca944fd6e3a99c
